#服务器端口
server:
  port: 9105

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

sidecar:
  # 异构微服务的IP
  ip: 40.73.3.16
  # 异构微服务的端口
  port: 80
  # 异构微服务的健康检查URL
#  health-check-url: http://localhost:8060/health.json

#management:
#  endpoint:
#    health:
#      show-details: always
